# Generated by Django 5.2.4 on 2025-07-08 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('desc', models.TextField()),
                ('address', models.TextField()),
                ('rooms', models.IntegerField()),
                ('image', models.ImageField(default='default/house.png', upload_to='apartments/')),
                ('price', models.DecimalField(decimal_places=2, help_text='$', max_digits=10)),
            ],
        ),
    ]
